### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by ChristianCortes** [lhhunghimself/fastBMA#5]
Hi,

I am running fastBMA in one machine with 16 cores and 500GB without MPI. I've tested your data using the following:

fastBMA -t -o 4 -n 16 -m /homes/users/ccortes/fastBMA/input/timeSeries.tab --edgeMin 0.5 --priorsList /homes/users/ccortes/fastBMA/input/reg.prob.list --noPrune --oddsRatio 100 --time --verbose

and I got:

Input Parameters: 
priorsList: /homes/users/ccortes/fastBMA/input/reg.prob.list
matrixFile: /homes/users/ccortes/fastBMA/input/timeSeries.tab
nThreads: 16
minimum edgeWeight: 0.5
g set to number of sqrt(nsamples)
g optimized: 4 bits
g maxOptimizeCycles: 20
matrix interpreted as time series
Uninformed Prior: 0.00046
oddsRatio: 100
Do not show edges to same node
All variables used
verbose on
Do no remove redundant direct edges 
Segmentation fault (core dumped)

Also if I run fastBMA with my data in the same machine I got:

fastBMA -t -o 4 -n 16 -m /homes/users/ccortes/fastBMA/input/gData_filtered_arcsine_expN.txt --edgeMin 0.5 --priorsList /homes/users/ccortes/fastBMA/input/wedgelist_reactome_gData_filtered_graphite.txt --residuals --showPrune --verbose --time
Input Parameters: 
priorsList: /homes/users/ccortes/fastBMA/input/wedgelist_reactome_gData_filtered_graphite.txt
matrixFile: /homes/users/ccortes/fastBMA/input/gData_filtered_arcsine_expN.txt
nThreads: 16
minimum edgeWeight: 0.5
g set to number of sqrt(nsamples)
g optimized: 4 bits
g maxOptimizeCycles: 20
matrix interpreted as time series
Uninformed Prior: 0.00046
oddsRatio: 10000
Do not show edges to same node
All variables used
verbose on
Do no remove but indicate redundant direct edges 
terminate called after throwing an instance of 'std::bad_array_new_length'
  what():  std::bad_array_new_length
Aborted (core dumped)

I hope you can help me,

Thanks in advance,

Christian

**Comment by lhhunghimself** [comment]
Thanks for pointing this out.
I fixed the bug in the code reading the priors list and pushed the changes to the repo.
Recompile and try again and let me know if there are any more problems.

**Comment by ChristianCortes** [comment]
Thanks for fixing the bug, works perfectly when is run with the sample data. But still i get the same error when is run with my data.

fastBMA -t -o 4 -n 16 -m /homes/users/ccortes/fastBMA/input/gData_filtered_arcsine_expN.txt --edgeMin 0.5 --priorsList /homes/users/ccortes/fastBMA/input/wedgelist_reactome_gData_filtered_graphite.txt --residuals --showPrune --verbose --time
Input Parameters:
priorsList: /homes/users/ccortes/fastBMA/input/wedgelist_reactome_gData_filtered_graphite.txt
matrixFile: /homes/users/ccortes/fastBMA/input/gData_filtered_arcsine_expN.txt
nThreads: 16
minimum edgeWeight: 0.5
g set to number of sqrt(nsamples)
g optimized: 4 bits
g maxOptimizeCycles: 20
matrix interpreted as time series
Uninformed Prior: 0.00046
oddsRatio: 10000
Do not show edges to same node
All variables used
verbose on
Do no remove but indicate redundant direct edges
terminate called after throwing an instance of 'std::bad_array_new_length'
what(): std::bad_array_new_length
Aborted (core dumped)

Do you think that can be a RAM issue? the matrixFile is 9x2974 (row x col) and the priorsList is 6076x3 (row x col).

Thanks again
